### ISSUE TITLE
Code for MFN

### ISSUE THREAD

**Issue by saxenarohit** [A2Zadeh/MFN#2]
The repository is empty

**Comment by A2Zadeh** [comment]
@saxenarohit this is on top of my priorities right now. We will get this code to you in the next few days. Sorry for the delay.

**Comment by impredicative** [comment]
In GitHub, issues should typically not be closed until after they're resolved. It is premature to close them in anticipation of a resolution.

**Comment by A2Zadeh** [comment]
You are correct, however, I closed this since I included everyone in this thread in the one you originally commented on. I must ask you to kindly remain calm and constructive. Things may not seem as they are at first ;)
